config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'tasks', to: 'tasks#index'

  # get 'tasks/new', to: 'tasks#new'
  # post 'tasks', to: 'tasks#create'

  # get 'tasks/:id', to: 'tasks#show', as: :task

  # get    'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch  'tasks/:id', to: 'tasks#update'

  # delete 'tasks/:id', to: 'tasks#destroy'

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def update
   @task = Task.find(params[:id])
   @task.update(task_params)
   redirect_to tasks_path(@task)
  end

  def destroy
  end

end

private
def task_params
params.require(:task).permit(:title, :details)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_for @task do |f| %>
  <%= f.label :title, "Title:" %>
  <%= f.text_field :title %>
  <%= f.label :details, "Detail:" %>
  <%= f.text_field :details %>
  <%= f.submit%>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<% @tasks.each do |task| %>
  <form class="form-inline">
    <% complete = task.completed == true ? "checked" : "" %>
    <input type="checkbox" disabled <%= complete %>/>
    <h4><%= link_to task.title, task_path(task) %></h4>
  </form>
<% end %>

<p><%= link_to "Add a new task", tasks_new_path %></p>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for @task do |f| %>
  <%= f.label :title, "Title:" %>
  <%= f.text_field :title %>
  <%= f.label :details, "Detail:" %>
  <%= f.text_field :details %>
  <%= f.submit%>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title%></h1>

<button>><%= link_to "Update Task", edit_task_path(@task) %></button>

<h2><%= @task.details%></h2>

<% if @task.completed == false %>
  <form class="form-inline">
    <input type="checkbox">
    <%= "This task is not completed yet" %>
  </form>
<% else%>
  <form class="form-inline">
    <input type="checkbox" checked="checked">
    <%= "This task is completed" %>
  </form>
<% end %>

<p><%= link_to "Back to list", tasks_path %></p>